# Generated by Django 6.0.4 on 2026-04-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="professeur",
            name="grade",
            field=models.CharField(
                choices=[
                    ("MCA", "Maître de Conférences A"),
                    ("MCB", "Maître de Conférences B"),
                    ("PR", "Professeur"),
                    ("DR", "Docteur"),
                ],
                default="DR",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
